<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '34',
    'typeid' => '0',
    'title' => 'To Celebrate Nodka the First Oversea Exhibition in 2019 Successfully Held',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'aaaaaaaa',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/News/CompanyNews/2019/0613/13.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560416773',
    'updatetime' => '1560416779',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '34',
    'typeid' => '0',
    'title' => 'To Celebrate Nodka the First Oversea Exhibition in 2019 Successfully Held',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/News/CompanyNews/2019/0613/14.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560416782',
    'updatetime' => '1560416786',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '34',
    'typeid' => '0',
    'title' => 'To Celebrate Nodka the First Oversea Exhibition in 2019 Successfully Held',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'ffffffffffff',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/News/CompanyNews/2019/0613/18.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560420371',
    'updatetime' => '1560420375',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '34',
    'typeid' => '0',
    'title' => 'At Intel ® Spring Symposium, Nodka shared',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'Intel® Spring Symposium on New Technologies Assisting Industry 4 0 was successfully held at Xi’an Fuli Hilton Hotel on April 26th, 2019  At this meeting, Intel® shared the new technologies',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/News/CompanyNews/2019/0613/19.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560420398',
    'updatetime' => '1560420405',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>