<?php
return array (
  5 => 
  array (
    'id' => '5',
    'catid' => '62',
    'typeid' => '0',
    'title' => 'hfhjgkjgh',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Service/Download/2019/0618/5.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560865027',
    'updatetime' => '1560865059',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '',
    'language' => '',
    'classtype' => '',
    'version' => '',
    'filesize' => 'Unkown',
    'stars' => '',
    'hitsid' => 'c-2-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>