<?php
return array (
  15 => 
  array (
    'id' => '15',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'cccccccccc',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'cccccccc',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/Solutions/2019/0613/15.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560416946',
    'updatetime' => '1560416950',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'dddddddddddddddddddddddddddddddddddddddddddddddd',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'ddddddddddddddddddddddddddddddddddddd',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/Solutions/2019/0613/16.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560416952',
    'updatetime' => '1560416957',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'eeeee',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'eeeeeeeee',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/Solutions/2019/0613/17.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560420362',
    'updatetime' => '1560420366',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'hhhhhhhhhhhhhh',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/EN/Solutions/2019/0613/20.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560420410',
    'updatetime' => '1560420414',
    'hitsid' => 'c-1-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>