<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '20',
    'typeid' => '0',
    'title' => '解决方案-测试数据11111111',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '解决方案-测试数据11111111',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Solutions/2019/0613/8.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560400332',
    'updatetime' => '1560400346',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '20',
    'typeid' => '0',
    'title' => '解决方案-测试数据222222222',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '解决方案-测试数据222222',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Solutions/2019/0613/9.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560400350',
    'updatetime' => '1560400357',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '20',
    'typeid' => '0',
    'title' => '解决方案-测试数据3333333',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '解决方案-测试数据33333333',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Solutions/2019/0613/10.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560400360',
    'updatetime' => '1560400365',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '20',
    'typeid' => '0',
    'title' => '解决方案-测试数据444444',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '解决方案-测试数据4444444444',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Solutions/2019/0613/11.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560400368',
    'updatetime' => '1560400373',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '20',
    'typeid' => '0',
    'title' => '工业平板电脑在水闸泵站监控系统中的应用',
    'style' => '',
    'thumb' => 'http://www.unihmi.com/uploadfile/2019/0613/20190613123721769.jpg',
    'keywords' => '',
    'description' => '水闸泵站监控系统工程主要是为了对水闸泵站群的联合运行进行有效监视和控制保证闸门更加安全可靠运行监控系统综合利用成熟的工业控制技术传感器技术数据传输技术以及计算机技',
    'posids' => '0',
    'url' => 'http://www.unihmi.com/ZH/Solutions/2019/0613/12.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'unihmi',
    'inputtime' => '1560400377',
    'updatetime' => '1560400382',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>